class CreateReports < ActiveRecord::Migration
  def change
    create_table :reports do |t|
      t.string :create_user
      t.string :company_code
      t.string :branch_code
      t.string :location_code
      t.string :location_name
      t.string :mis_job_close_status
      t.string :segment_code
      t.string :segment_name
      t.string :job_no
      t.string :subjob_no
      t.string :create_date
      t.string :job_date
      t.string :job_month
      t.string :is_etd_confirmed
      t.string :etd
      t.string :eta
      t.string :atd
      t.string :ata
      t.string :connection_etd
      t.string :connection_eta
      t.string :connection_atd
      t.string :is_eta_confirmed
      t.string :sea_air
      t.string :mawb_obl_no
      t.string :mawb_obl_date
      t.string :is_co_load
      t.string :service_code
      t.string :job_completed_status
      t.string :date_of_mis_closure
      t.string :job_agent_name
      t.string :origin_agent_name
      t.string :fdc_agent_name
      t.string :agent_name
      t.string :carrier_code
      t.string :carrier_name
      t.string :vessel_name
      t.string :flight_no
      t.string :flight_date
      t.string :co_loader_name
      t.string :hawb_hbl_no
      t.string :hawb_hbl_date
      t.string :import_clearance_date
      t.string :tos_code
      t.string :door_delivery
      t.string :personal_effect
      t.string :uc_no
      t.string :imo_un_no
      t.string :imo_code
      t.string :transporter_name
      t.string :do_no
      t.string :do_date
      t.string :do_issued_by
      t.string :bl_released_user
      t.string :bl_received_date
      t.string :trade_code
      t.string :origin_country_name
      t.string :origin_sector_name
      t.string :origin_port
      t.string :origin_port_name
      t.string :pol_country_name
      t.string :pol
      t.string :pol_port_name
      t.string :pod
      t.string :pod_country_name
      t.string :pod_port_name
      t.string :fdc_country_name
      t.string :fdc_region_name
      t.string :fdc
      t.string :fdc_port_name
      t.string :house_pp_cc
      t.string :who_routed
      t.string :is_co_loader_shipment
      t.string :project_code
      t.string :customs_cleared_by_us
      t.string :clearance_note
      t.string :shipper_name
      t.string :shipper_address
      t.string :consignee_name
      t.string :consignee_address
      t.string :forwarder_name
      t.string :forwarder_address
      t.string :notify_name
      t.string :notify_address
      t.string :customer_group_code
      t.string :customer_name
      t.string :industry_name
      t.string :container_no
      t.string :chargeable_weight
      t.string :gross_weight
      t.string :cbm
      t.string :teu
      t.string :no_of_pkgs
      t.string :cfs_name
      t.string :job_sales_location
      t.string :salesman_name
      t.string :routed_by_agent_name
      t.string :origin_booking_no
      t.string :origin_booking_location
      t.string :origin_booking_person
      t.string :fdc_booking_no
      t.string :fdc_booking_location
      t.string :fdc_booking_person
      t.string :subjob_status
      t.string :frt_revenue
      t.string :rebate_revenue
      t.string :storage_revenue
      t.string :other_revenue
      t.string :frt_cost
      t.string :rebate_cost
      t.string :other_cost
      t.string :neutral
      t.string :net
      t.string :transhipment_net
      t.string :out_gate_time_delivery_date
      t.string :date_of_job_completed
      t.string :bill_of_entry
      t.string :decleration_no
      t.string :boe_date
      t.string :number_of_grid
      t.string :cost_center_code
      t.string :oa_number

      t.timestamps
    end
  end
end
